### ISSUE TITLE
SLAE: CRS на ВСЕМ

### ISSUE THREAD

**Issue by DreamTeamForever** [DreamTeamForever/SlaeSolvers#10]
CRS сейчас самый ущербный формат. Надо допилить

**Comment by DSpythonvitalay** [comment]
СRS работает на тестах 1,7-12 .Все методы.Без ПО и диагональным ПО.Lu новое , не тестил пока.

**Comment by LibrechtIsTheBest** [comment]
Не знаю, имеет ли смысл это писать, но все же.
Касательно наших (старых) тестов для CRS:
LOS LU, MSG LU/Diag, BSG LU/Diag, BSG_STAB LU/Diag - работают на всех тестах.

Не правильные ответы:
LOS 2, 15, 16                        // (15, 16) - нули на диагонали, и без ПО их не обнаружить
LOS Diag 2
BSG 15
BSG_STAB 15
MSG 2, 3, 6, 15, 16               // но (2, 3, 6) - несимметричные
Seidel 2,3,6,14,15,16            // 14 - тоже нули на диагонали, 3 тест решается если relax = 0.1 например. 6 тест решается при relax <= 1.2
Jacobi 2,3,14,15,16 (relax = 1)
