### ISSUE TITLE
Тест, который сломал все.

### ISSUE THREAD

**Issue by AnnieBC** [DreamTeamForever/SlaeSolvers#13]
11й тест для формата CRCS не то что не решился ни одни решателем, программа вылетела. Он всего лишь 3*3. 
P.S.: В массиве al присутствует 0.

**Comment by mangusttank** [comment]
Судя по ial.txt в последней сроке должно стоять два числа, в al.txt тоже стоит два числа (1 0), но в массиве jal.txt только одно (1).
Программа выкидывает исключение "Invalid data: al.size() != jal.size()", что мы и наблюдаем в самом тесте.

**Comment by AnnieBC** [comment]
в jal тоже 2!
https://github.com/DreamTeamForever/SlaeSolvers/blob/crash_all_solvers_crcs11/Tests/Formats/CRCS/11/jal.txt

**Comment by AnnieBC** [comment]
сама матрица:
2	0	1
0	2	0
1	0	2

di:	2	2	2
al:	1	0		
au:	1			
ial: 0	0	0	2
iau: 0	0	0	1
jal: 0	1		
jau: 0

**Comment by AnnieBC** [comment]
сама матрица:
2	0	1
0	2	0
1	0	2

di:	2	2	2
al:	1	0		
au:	1			
ial: 0	0	0	2
iau: 0	0	0	1
jal: 0	1		
jau: 0

**Comment by mangusttank** [comment]
В ветке master лежит неправильный jal.txt значит.
https://github.com/DreamTeamForever/SlaeSolvers/blob/master/Tests/Formats/CRCS/11/jal.txt
И jau.txt тоже
https://github.com/DreamTeamForever/SlaeSolvers/blob/master/Tests/Formats/CRCS/11/jau.txt

Я только что запустил с исправленными файлами на LOS.
Ответ: 1 2 3 
Все сработало без проблем.
