### ISSUE TITLE
Solvers: Количество итераций ( различные ) для зейделя и якоби на разных форматах

### ISSUE THREAD

**Issue by DreamTeamForever** [DreamTeamForever/SlaeSolvers#3]
Протестировать для разных форматах методы Зейдель и Якоби на количество итераций, проверить и понять почему так.

**Comment by aprokof** [comment]
Проблема устранена ( возникла случайно). При изучение результатов автотестирования было замечено, что количество итераций одно.

**Comment by DreamTeamForever** [comment]
Случайно это как? Магнитные бури?
