### ISSUE TITLE
Solvers : проблема выдача  IND 

### ISSUE THREAD

**Issue by DreamTeamForever** [DreamTeamForever/SlaeSolvers#4]
Добавить проверки на обработку  деление на ноль  в решателях (всех типах) : невязка, нулевых скалярах

**Comment by aprokof** [comment]
На данный момент обработана ситуация при делении на 0 в вычислении невязки. Обсуждается, необходимо ли проверять деления на 0 при вычислении alpha, betta.

**Comment by aprokof** [comment]
Добавлены проверки деления на 0 при вычислении скаляров alpha, betta

**Comment by aprokof** [comment]
Исправлены проверки:   std::numeric_limits<double>::epsilon() заменила на 1е-30. так как при некоторых тестах  std::numeric_limits<double>::epsilon() было недостаточно, и когда есть решение выдавал "ошибка -деление на 0"
