### ISSUE TITLE
SLAE: Dense LU

### ISSUE THREAD

**Issue by DreamTeamForever** [DreamTeamForever/SlaeSolvers#9]
разобраться, почему такое большое количество итераций на msg lu

**Comment by aprokof** [comment]
Я с этим разобралась, были ошибки в LSolveT, USolveT- поправила . Вероника в курсе, сказала,что сегодня их посмотрит и скажет,что по этому поводу она думает.

**Comment by veronikabochkova** [comment]
Я посмотрела, со всеми исправлениями согласна. Добавьте изменения Алины в основную ветку.

**Comment by DreamTeamForever** [comment]
Слито
